//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskmange
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string userNameAdmin { get; set; }
        public string userNameEmp { get; set; }
        public string userPasswordAdmin { get; set; }
        public string userPasswordEmp { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    }
}
